In this notebook, I'll be evaluating the contigency tables generated with the response data by applying fisher exact tests

In [2]:
x <- matrix(c(2, 1, 0, 9, 5, 0, 6, 0, 1), byrow = TRUE, nrow = 3, ncol = 3);
print(x)
fisher.test(x);

     [,1] [,2] [,3]
[1,]    2    1    0
[2,]    9    5    0
[3,]    6    0    1



	Fisher's Exact Test for Count Data

data:  x
p-value = 0.2173
alternative hypothesis: two.sided


In [3]:
x1 <- matrix(c(2, 1, 9, 5, 6, 0), byrow = TRUE, nrow = 3, ncol = 2);
print(x1)
fisher.test(x1);

     [,1] [,2]
[1,]    2    1
[2,]    9    5
[3,]    6    0



	Fisher's Exact Test for Count Data

data:  x1
p-value = 0.2545
alternative hypothesis: two.sided


In [4]:
x2 <- matrix(c(2, 1, 0, 15, 5, 1), byrow = TRUE, nrow = 2, ncol = 3);
print(x2)
fisher.test(x2);

     [,1] [,2] [,3]
[1,]    2    1    0
[2,]   15    5    1



	Fisher's Exact Test for Count Data

data:  x2
p-value = 1
alternative hypothesis: two.sided


In [5]:
x3 <- matrix(c(2, 1, 15, 5), byrow = TRUE, nrow = 2, ncol = 2);
print(x3)
fisher.test(x3);

     [,1] [,2]
[1,]    2    1
[2,]   15    5



	Fisher's Exact Test for Count Data

data:  x3
p-value = 1
alternative hypothesis: true odds ratio is not equal to 1
95 percent confidence interval:
  0.028988 47.111229
sample estimates:
odds ratio 
 0.6793983 


In [6]:
x4 <- matrix(c(28,24,3,14,14,2,7,0,1), byrow = TRUE, nrow = 3, ncol = 3);
print(x4)
fisher.test(x4);

     [,1] [,2] [,3]
[1,]   28   24    3
[2,]   14   14    2
[3,]    7    0    1



	Fisher's Exact Test for Count Data

data:  x4
p-value = 0.08969
alternative hypothesis: two.sided


In [7]:
x5 <- matrix(c(28,24,14,14,7,0), byrow = TRUE, nrow = 3, ncol = 2);
print(x5)
fisher.test(x5);

     [,1] [,2]
[1,]   28   24
[2,]   14   14
[3,]    7    0



	Fisher's Exact Test for Count Data

data:  x5
p-value = 0.04224
alternative hypothesis: two.sided


In [8]:
x6 <- matrix(c(28,24,3,21,14,3), byrow = TRUE, nrow = 2, ncol = 3);
print(x6)
fisher.test(x6);

     [,1] [,2] [,3]
[1,]   28   24    3
[2,]   21   14    3



	Fisher's Exact Test for Count Data

data:  x6
p-value = 0.7487
alternative hypothesis: two.sided


In [9]:
x7 <- matrix(c(28,24,21,14), byrow = TRUE, nrow = 2, ncol = 2);
print(x7)
fisher.test(x7);

     [,1] [,2]
[1,]   28   24
[2,]   21   14



	Fisher's Exact Test for Count Data

data:  x7
p-value = 0.6612
alternative hypothesis: true odds ratio is not equal to 1
95 percent confidence interval:
 0.2966743 2.0166748
sample estimates:
odds ratio 
 0.7800311 


In [10]:
x8 <- matrix(c(13,4,3,12,2,1), byrow = TRUE, nrow = 2, ncol = 3);
print(x8)
fisher.test(x8);

     [,1] [,2] [,3]
[1,]   13    4    3
[2,]   12    2    1



	Fisher's Exact Test for Count Data

data:  x8
p-value = 0.6459
alternative hypothesis: two.sided


In [12]:
x9 <- matrix(c(13,4,12,2), byrow = TRUE, nrow = 2, ncol = 2);
print(x9)
fisher.test(x9);

     [,1] [,2]
[1,]   13    4
[2,]   12    2



	Fisher's Exact Test for Count Data

data:  x9
p-value = 0.6638
alternative hypothesis: true odds ratio is not equal to 1
95 percent confidence interval:
 0.04254544 4.70345445
sample estimates:
odds ratio 
 0.5522437 


In [13]:
x10 <- matrix(c(13,4,3,10,10,1), byrow = TRUE, nrow = 2, ncol = 3);
print(x10)
fisher.test(x10);

     [,1] [,2] [,3]
[1,]   13    4    3
[2,]   10   10    1



	Fisher's Exact Test for Count Data

data:  x10
p-value = 0.1895
alternative hypothesis: two.sided


In [14]:
x11 <- matrix(c(13,4,10,10), byrow = TRUE, nrow = 2, ncol = 2);
print(x11)
fisher.test(x11);

     [,1] [,2]
[1,]   13    4
[2,]   10   10



	Fisher's Exact Test for Count Data

data:  x11
p-value = 0.1734
alternative hypothesis: true odds ratio is not equal to 1
95 percent confidence interval:
  0.6546843 18.0757350
sample estimates:
odds ratio 
  3.144907 
